Fix: remove the check for the Server header of the Instana agent.
instana/python-sensor pull request #427
Opened 2023-05-22 15:07 UTC by pvital

The check for the Server header of the Instana agent can break the announce procedure in service meshes when there is a proxy between the tracer and the Instana agent. This happens because some proxies do not forward the original Server header. So instead, the collector checks whether the HTTP status code is in the 2xx range.

2023-05-22 15:36 UTC, basti1302 reviewed
Looks good. We should double check the timeout change, see inline comment.

2023-05-22 15:36 UTC, basti1302 commented on instana/agent/host.py
> +            response = self.client.get(url, timeout=5000)
_issue:_ If I read https://requests.readthedocs.io/en/latest/user/advanced/#timeouts correctly, the timeout is specified as the number of seconds, not milliseconds. That is probably why it was 0.8 before? 5000 _seconds_ would be a really long timeout. 5 seconds would be good I guess.

2023-05-23 18:02 UTC, Ferenc- requested changes
Good work so far. We are getting there.
The [coverage report shows](https://output.circle-artifacts.com/output/job/27c6f31a-d745-446b-81cf-c91f480b88eb/artifacts/0/htmlcov/d_8932aa06527cfb99_host_py.html#t161) that the failed attempt is nicely covered with the test case,
while the successful attempt is not yet covered.

Although the production code around the succesful attempt is minuscule.
I still think covering the succesful attempt would be valuable, not just because we can't have a functioning system without a successful connection attempts,
but also because this change is about enabling successful connections in a broader situation.
so any other change is secondary priority here.

2023-05-23 18:06 UTC, Ferenc- commented on tests/platforms/test_host.py
> +import requests_mock
Where do we use this?

2023-05-25 09:34 UTC, Ferenc- approved these changes
Approved

2023-05-25 09:34 UTC, merged