test: Add tests for CTX manager usage on PEP0249.
instana/python-sensor pull request #448
Opened 2023-08-30 13:54 UTC by pvital

Add the test_connect_ctx_mngr UT to test the span creation when using the psycopg2 connect with context manager, and the test_connect_cursor_ctx_mngr UT when using the psycopg2 connect and cursos context manager.

2023-08-30 14:28 UTC, Ferenc- requested changes
Please add a TC where the db is not managed, but the cursor is.
Please cover the rest of the instrumentations where PEP0248 is used, like mysql.

2023-08-31 06:27 UTC, GSVarsha commented
Hi @pvital , I'm also working on the same changes as you're doing here in this PR.
[This](https://github.com/instana/python-sensor/tree/context_mgr_test) is my branch.
I've also covered `pymysql` and `mysqlclient` here.

2023-08-31 07:44 UTC, pvital commented
I am closing this PR once we use #449 to track this fix.

2023-08-31 07:44 UTC, closed without merging

2023-08-31 07:44 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        self.assertEqual(None, db_span.ec)
This should be [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=assertisnone#unittest.TestCase.assertIsNone)

2023-08-31 07:45 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        self.assertEqual(None, db_span.ec)
This should be [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=assertisnone#unittest.TestCase.assertIsNone)

2023-08-31 07:45 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        self.assertEqual(None, db_span.ec)
This should be [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=assertisnone#unittest.TestCase.assertIsNone)

2023-08-31 07:45 UTC, Ferenc- commented on tests/clients/test_psycopg2.py
> +        self.assertEqual(None, db_span.ec)
This should be [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=assertisnone#unittest.TestCase.assertIsNone)

2023-08-31 07:45 UTC, Ferenc- commented on tests/clients/test_psycopg2.py
> +        self.assertEqual(None, db_span.ec)
This should be [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=assertisnone#unittest.TestCase.assertIsNone)

2023-08-31 07:45 UTC, Ferenc- commented on tests/clients/test_psycopg2.py
> +        self.assertEqual(None, db_span.ec)
This should be [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=assertisnone#unittest.TestCase.assertIsNone)

2023-08-31 07:46 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        self.assertEqual(None, db_span.ec)
This should be [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=assertisnone#unittest.TestCase.assertIsNone)

2023-08-31 07:46 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        self.assertEqual(None, db_span.ec)
This should be [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=assertisnone#unittest.TestCase.assertIsNone)

2023-08-31 07:51 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        assert(result >= 0)
This `assert` is for catching runtime anomalies in the production code, after it is deployed.
For unit testing we should use [assertTrue](https://docs.python.org/3/library/unittest.html?highlight=assertisnone#unittest.TestCase.assertTrue), if nothing else fits better.

2023-08-31 07:54 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        assert(result >= 0)
This `assert` is for catching runtime anomalies in the production code, after it is deployed.
For unit testing we should use [assertTrue](https://docs.python.org/3/library/unittest.html?highlight=assertisnone#unittest.TestCase.assertTrue), if nothing else fits better.

2023-08-31 07:54 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        assert(result >= 0)
This `assert` is for catching runtime anomalies in the production code, after it is deployed.
For unit testing we should use [assertTrue](https://docs.python.org/3/library/unittest.html?highlight=assertisnone#unittest.TestCase.assertTrue), if nothing else fits better.

2023-08-31 07:54 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        assert(result >= 0)
This `assert` is for catching runtime anomalies in the production code, after it is deployed.
For unit testing we should use [assertTrue](https://docs.python.org/3/library/unittest.html?highlight=assertisnone#unittest.TestCase.assertTrue), if nothing else fits better.

2023-08-31 07:55 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        assert(result >= 0)
This `assert` is for catching runtime anomalies in the production code, after it is deployed.
For unit testing we should use [assertTrue](https://docs.python.org/3/library/unittest.html?highlight=assertisnone#unittest.TestCase.assertTrue), if nothing else fits better.

2023-08-31 07:59 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        result = None
The context manager does not create a new scope, the `result = cursor.execute(` statement is enough. Please remove this line, luckily this is not Pascal or ANSI C, where you have to declare the variables way ahead of assigning them.

2023-08-31 07:59 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        result = None
Please remove.

2023-08-31 07:59 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        result = None
Please remove.

2023-08-31 07:59 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        result = None
Please remove.

2023-08-31 07:59 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        result = None
Please remove.

2023-08-31 07:59 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        result = None
Please remove.

2023-08-31 08:00 UTC, Ferenc- reviewed
This is just a preliminary review. With some minor formalities commented for now.

2023-08-31 08:10 UTC, pvital commented
@Ferenc- as mentioned [here](https://github.com/instana/python-sensor/pull/448#issuecomment-1700529840), this PR is closed. Thanks anyway.