Add ctx manager tests for pep249 based db modules
instana/python-sensor pull request #450
Opened 2023-08-31 07:11 UTC by GSVarsha

Add context manager tests to db modules that conform to PEP-249

psycopg2
pymysql
mysqlclient

2023-08-31 07:31 UTC, GSVarsha commented
<img width="1327" alt="Screenshot 2023-08-31 at 1 01 19 PM" src="https://github.com/instana/python-sensor/assets/52667690/1090925d-2376-4245-8a1a-84c18423544d">

2023-08-31 07:42 UTC, pvital approved these changes
LGTM. Great job @GSVarsha.

2023-08-31 08:09 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        result = None
This is not needed please remove.

2023-08-31 08:09 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        result = None
This is not needed please remove.

2023-08-31 08:09 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        result = None
This is not needed please remove.

2023-08-31 08:10 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        result = None
This is not needed please remove.

2023-08-31 08:10 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        result = None
This is not needed please remove.

2023-08-31 08:10 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        result = None
This is not needed please remove.

2023-08-31 08:11 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        assert result >= 0
This assert is for production codes runtime anomalies. For unit tests please use from the `unittest` module, if nothing else fits then [assertTrue](https://docs.python.org/3/library/unittest.html?highlight=asserttrue#unittest.TestCase.assertTrue)

2023-08-31 08:12 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        assert result >= 0
This assert is for production codes runtime anomalies. For unit tests please use from the `unittest` module, if nothing else fits then [assertTrue](https://docs.python.org/3/library/unittest.html?highlight=asserttrue#unittest.TestCase.assertTrue)

2023-08-31 08:12 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        assert result >= 0
This assert is for production codes runtime anomalies. For unit tests please use from the `unittest` module, if nothing else fits then [assertTrue](https://docs.python.org/3/library/unittest.html?highlight=asserttrue#unittest.TestCase.assertTrue)

2023-08-31 08:12 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        assert result >= 0
This assert is for production codes runtime anomalies. For unit tests please use from the `unittest` module, if nothing else fits then [assertTrue](https://docs.python.org/3/library/unittest.html?highlight=asserttrue#unittest.TestCase.assertTrue)

2023-08-31 08:12 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        assert result >= 0
This assert is for production codes runtime anomalies. For unit tests please use from the `unittest` module, if nothing else fits then [assertTrue](https://docs.python.org/3/library/unittest.html?highlight=asserttrue#unittest.TestCase.assertTrue)

2023-08-31 08:13 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        self.assertEqual(None, db_span.ec)
Please use [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=asserttrue#unittest.TestCase.assertIsNone)

2023-08-31 08:13 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        self.assertEqual(None, db_span.ec)
Please use [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=asserttrue#unittest.TestCase.assertIsNone)

2023-08-31 08:13 UTC, Ferenc- commented on tests/clients/test_mysqlclient.py
> +        self.assertEqual(None, db_span.ec)
Please use [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=asserttrue#unittest.TestCase.assertIsNone)

2023-08-31 08:13 UTC, Ferenc- commented on tests/clients/test_psycopg2.py
> +        self.assertEqual(None, db_span.ec)
Please use [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=asserttrue#unittest.TestCase.assertIsNone)

2023-08-31 08:13 UTC, Ferenc- commented on tests/clients/test_psycopg2.py
> +        self.assertEqual(None, db_span.ec)
Please use [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=asserttrue#unittest.TestCase.assertIsNone)

2023-08-31 08:14 UTC, Ferenc- commented on tests/clients/test_psycopg2.py
> +        self.assertEqual(None, db_span.ec)
Please use [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=asserttrue#unittest.TestCase.assertIsNone)

2023-08-31 08:14 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        self.assertEqual(None, db_span.ec)
Please use [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=asserttrue#unittest.TestCase.assertIsNone)

2023-08-31 08:14 UTC, Ferenc- commented on tests/clients/test_pymysql.py
> +        self.assertEqual(None, db_span.ec)
Please use [assertIsNone](https://docs.python.org/3/library/unittest.html?highlight=asserttrue#unittest.TestCase.assertIsNone)

2023-08-31 08:16 UTC, Ferenc- requested changes
For now, some comments on implementation details.

2023-08-31 08:26 UTC, Ferenc- requested changes
So far this PR is logically one change, which should be revertable and cherry-pick -able in one commit. But it is broken down to two commits. The second is correcting formalities of the first one, which carries the main value. So in the git history we would have to check multiple commits to get to one valuable change.

I suggest to put all these changes here in this case into one commit. Feel free to force push onto PR branches.
And consider make separate commits, if we deliver value separately, and or it makes sense to revert them separately if there is a need.

2023-08-31 09:59 UTC, Ferenc- requested changes
So we essentially have the reformatting back again?

2023-08-31 10:48 UTC, GSVarsha commented
> So we essentially have the reformatting back again?

Accidentally picked the wrong commit during rebase earlier. Should be good now.

2023-09-01 07:53 UTC, Ferenc- approved these changes

2023-09-01 07:53 UTC, merged