Django: capture responseHeadersOnEntrySpans
instana/python-sensor pull request #489
Opened 2023-12-28 11:13 UTC by GSVarsha

Django: capture responseHeadersOnEntrySpans

Signed-off-by: Varsha GS [varsha.gs@ibm.com](mailto:varsha.gs@ibm.com)

2023-12-29 08:28 UTC, Ferenc- commented on instana/instrumentation/django/middleware.py
> +            if agent.options.extra_http_headers is not None:
This check should be inverted for an early return and should go touside of the `try` block.

2023-12-29 08:33 UTC, Ferenc- commented on tests/apps/app_django.py
> +    return response
```suggestion
    return HttpResponse('Stan wuz here with headers!', headers={'X-Capture-This-Too': 'this too'})
```

2023-12-29 08:37 UTC, Ferenc- commented on tests/apps/app_django.py
> +    return response
I think it is still safer if we cover the capture of a list of headers, and not just a single header. Although the `test_request_header_capture` tests with a list and currently that covers the same codepath, but that is an implementational detail which at least theoretically could change in the future.

2023-12-29 08:37 UTC, Ferenc- commented on tests/frameworks/test_django.py
> +        agent.options.extra_http_headers = [u'X-Capture-This-Too']
I think it is safer to test with more than one headers at a time.

2023-12-29 08:39 UTC, Ferenc- commented on tests/frameworks/test_django.py
> +        assert response
I know this was all over this TS, but this should really be `self.assertTrue`.

2023-12-29 08:40 UTC, Ferenc- commented on tests/frameworks/test_django.py
> +        assert "X-Capture-This-Too" in django_span.data["http"]["header"]
```suggestion
        self.assertIn( "X-Capture-This-Too", django_span.data["http"]["header"])
```

2023-12-29 08:42 UTC, Ferenc- commented on tests/frameworks/test_django.py
> +
If we had another header to capture, then we could validate it here.

2023-12-29 08:43 UTC, Ferenc- requested changes
Good job! I have suggested a few minor changes.

2023-12-29 13:57 UTC, Ferenc- approved these changes
LGTM

2024-01-02 10:51 UTC, pvital approved these changes
It looks good to me.

2024-01-02 11:14 UTC, merged