chore: Drop 3.7 support
instana/python-sensor pull request #542
Opened 2024-06-12 09:35 UTC by Ferenc-

This is needed for multiple reasons,
most pressing is that the `importlib.metadata` is only available in 3.8, and that would be needed to fix deprecation warnings about `pkg_resources`.

2024-06-12 09:44 UTC, GSVarsha requested changes
Should we consider removing 3.7 from [here](https://github.com/instana/python-sensor/blob/drop-37/bin/aws-lambda/build_and_publish_lambda_layer.py#L134) as well?

2024-06-12 09:50 UTC, Ferenc- commented
> Should we consider removing 3.7 from [here](https://github.com/instana/python-sensor/blob/drop-37/bin/aws-lambda/build_and_publish_lambda_layer.py#L134) as well?

Yes, that should have been removed [long ago](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).

2024-06-12 10:13 UTC, GSVarsha requested changes
Can we remove [this](https://github.com/instana/python-sensor/blob/drop-37/.tekton/run_unittests.sh#L22) because someone 3.7 is getting picked up by the [CI runs](http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/default/pipelineruns/python-tracer-pr-drop-37-84e9256?pipelineTask=unittest-default&taskRunName=python-tracer-pr-drop-37-84e9256-unittest-default-0&step=unittest).

2024-06-12 10:38 UTC, GSVarsha requested changes
Can we remove all the branching for 3.7?

<img width="605" alt="Screenshot 2024-06-12 at 4 02 56 PM" src="https://github.com/instana/python-sensor/assets/52667690/9ddbcb21-e1bc-4a25-aecf-e3472482dc48">
<img width="585" alt="Screenshot 2024-06-12 at 4 04 48 PM" src="https://github.com/instana/python-sensor/assets/52667690/e5df7603-00ec-4a80-a373-d4ce1ffbb92a">

2024-06-12 12:23 UTC, pvital requested changes
Perhaps you can also remove the `tests/requirements-307.txt` file in this PR.

2024-06-12 15:25 UTC, pvital requested changes

2024-06-12 15:25 UTC, pvital commented on tests/requirements-308.txt
Isn't the `requirements.txt` file the one to use on top of Python 3.8 and 3.9? 
It would be better to delete the `requirements-307.txt` and keep the `requirements.txt` one. Don't you think?

2024-06-12 15:34 UTC, Ferenc- commented on tests/requirements-308.txt
This wasn't needed, this remained in the commit by mistake. Removed now.

2024-06-12 16:02 UTC, pvital approved these changes
It looks good to me.

2024-06-13 03:53 UTC, GSVarsha approved these changes
LGTM

2024-06-13 03:54 UTC, merged