[OTel] Refactor couchbase instrumentation
instana/python-sensor pull request #611
Opened 2024-09-09 06:56 UTC by CagriYonca

Coverage: 96%

2024-09-12 12:22 UTC, pvital requested changes
Few suggestions.

2024-09-12 12:22 UTC, pvital commented on src/instana/instrumentation/couchbase_inst.py
> +        query_arg: Any,
Is there something better than `Any`?

2024-09-12 12:22 UTC, pvital commented on src/instana/instrumentation/couchbase_inst.py
>                  if type(query_arg) is N1QLQuery:
Look, you have a hint for `query_arg`'s type here!

2024-09-12 12:22 UTC, pvital commented on src/instana/instrumentation/couchbase_inst.py
> +        ) -> Any:
```suggestion
        ) -> object:
```

2024-09-12 12:22 UTC, pvital commented on src/instana/instrumentation/couchbase_inst.py
>                  except Exception as e:
Use the following expression along your file (and all other instrumentation) and skip this block for coverage counting:
```suggestion
                except Exception as exc:
```

2024-09-12 12:22 UTC, pvital commented on src/instana/instrumentation/couchbase_inst.py
> +    ):
Missing return type annotation.

2024-09-12 13:23 UTC, pvital commented on src/instana/instrumentation/couchbase_inst.py
> +        query_arg: Any,
If there is no way to check which other type is coming, then I prefer `Union[N1QLQuery, object]`.

2024-09-13 08:20 UTC, GSVarsha commented on src/instana/instrumentation/couchbase_inst.py
> +    ):
Can we make it simpler?

```suggestion
if not hasattr(couchbase, "__version__") and (couchbase.__version__ < "2.3.4" or couchbase.__version__ >= "3.0.0"):
```

2024-09-13 08:28 UTC, GSVarsha requested changes
Small suggestion.

2024-09-18 08:41 UTC, GSVarsha approved these changes
Looks good to me!

2024-09-18 08:53 UTC, merged