[OTel] Refactor cassandra instrumentation
instana/python-sensor pull request #616
Opened 2024-09-11 07:32 UTC by CagriYonca

Coverage: 96%

2024-09-12 12:49 UTC, pvital requested changes
Very few requests :-D

2024-09-12 12:49 UTC, pvital commented on src/instana/instrumentation/cassandra_inst.py
> +    ) -> Any:
```suggestion
    ) -> object:
```

2024-09-12 13:03 UTC, CagriYonca commented on src/instana/instrumentation/cassandra_inst.py
> +    ) -> Any:
Done

2024-09-18 08:45 UTC, GSVarsha approved these changes
LGTM!

2024-09-18 09:06 UTC, merged