[OTel] PubSub & Cloud Storage instrumentation
instana/python-sensor pull request #623
Opened 2024-09-20 13:53 UTC by CagriYonca

- Pubsub coverage: 90%
- Cloud Storage coverage: 91%

2024-09-24 08:16 UTC, GSVarsha commented on src/instana/instrumentation/google/cloud/storage.py
> +                tags = _collect_attributes(kwargs)
```suggestion
                attributes = _collect_attributes(kwargs)
```

2024-09-24 08:22 UTC, GSVarsha reviewed
A few minor requests. If there are other higher priority tasks, please feel free to make these changes later as well.

2024-09-25 09:07 UTC, pvital requested changes
In addition to @GSVarsha's requests, I have only one that should be applied to multiple files.

2024-09-27 09:28 UTC, CagriYonca commented on src/instana/instrumentation/google/cloud/storage.py
> +                tags = _collect_attributes(kwargs)
Done

2024-09-27 09:31 UTC, CagriYonca commented on tests/clients/test_google-cloud-pubsub.py
> +        assert gcps_span.k.value == 2
Done

2024-09-27 09:33 UTC, CagriYonca commented on src/instana/instrumentation/google/cloud/pubsub.py
> +from instana.span.span import InstanaSpan
Done

2024-09-27 09:34 UTC, CagriYonca commented on src/instana/instrumentation/google/cloud/pubsub.py
> +        span: InstanaSpan,
Done

2024-09-30 08:37 UTC, GSVarsha approved these changes
LGTM!

2024-09-30 08:54 UTC, merged