enhancement: Combine all requirements into single file
instana/python-sensor pull request #651
Opened 2024-10-15 14:00 UTC by CagriYonca

Combined all requirements into a single file, and added python version conditions.

2024-10-17 13:44 UTC, pvital requested changes
Few requests and comments.

2024-10-17 13:44 UTC, pvital commented on tests/requirements.txt
> +google-cloud-pubsub>=2.0.0; python_version < "3.12"
Shouldn't it be 3.13?
```suggestion
google-cloud-pubsub>=2.0.0; python_version < "3.13"
```

2024-10-17 13:44 UTC, pvital commented on tests/requirements.txt
> +google-cloud-storage>=1.24.0; python_version < "3.12"
```suggestion
google-cloud-storage>=1.24.0; python_version < "3.13"
```

2024-10-17 13:44 UTC, pvital commented on tests/requirements.txt
> +markupsafe>=2.1.0;python_version >= "3.10"
What are the versions for Python 3.8 and 3.9?

2024-10-17 13:44 UTC, pvital commented on tests/requirements.txt
> +starlette>=0.38.2; python_version == "3.13"
```suggestion
starlette>=0.12.13
```

2024-10-24 09:46 UTC, GSVarsha approved these changes
LGTM

2024-10-24 10:04 UTC, pvital approved these changes
It looks good to me.

2024-10-24 10:25 UTC, merged