fix(currency): run google-cloud-storage v2.18.2 separately for python 3.11
instana/python-sensor pull request #662
Opened 2024-10-28 13:19 UTC by CagriYonca

2024-10-28 13:30 UTC, pvital requested changes
Wait. You have just removed the job that runs GoogleCloud in the commit b7d66d1. 
Why you are re-introducing it again?

2024-10-29 10:37 UTC, pvital approved these changes
It looks good to me.

2024-10-30 06:32 UTC, GSVarsha commented on tests/requirements.txt
> +google-cloud-storage>=1.24.0; python_version < "3.11" or python_version > "3.11"
```suggestion
google-cloud-storage>=1.24.0; python_version != "3.11"
```

2024-10-30 06:42 UTC, GSVarsha requested changes
Hi @CagriYonca, I don't quite understand the intention behind this PR.

[This](https://github.com/instana/python-sensor/pull/662/files#diff-27c5febcc9ce93e8e5341f263b7d68962733b8a2a86c583723d025a1db39d7a3R17) change doesn't reflect the title of the PR: `"run google-cloud-storage v2.18.2 separately for python 3.11"`.

The commit message: [combined requirement files into one file and updated pipelines](https://github.com/instana/python-sensor/pull/662/commits/133485d0432203a71b30afe3444c7fd06d4bf981) also refers to something else.

2024-10-30 08:58 UTC, CagriYonca commented
> Hi @CagriYonca, I don't quite understand the intention behind this PR.
> 
> [This](https://github.com/instana/python-sensor/pull/662/files#diff-27c5febcc9ce93e8e5341f263b7d68962733b8a2a86c583723d025a1db39d7a3R17) change doesn't reflect the title of the PR: `"run google-cloud-storage v2.18.2 separately for python 3.11"`.
> 
> The commit message: [combined requirement files into one file and updated pipelines](https://github.com/instana/python-sensor/pull/662/commits/133485d0432203a71b30afe3444c7fd06d4bf981) also refers to something else.

It's just a fıx for fıx_requirements branch, I'll update the commit message right now

2024-11-04 10:23 UTC, GSVarsha commented on tests/requirements-googlecloud.txt
> +google-api-core>=2.15.0
You can remove this since it is already required by `gcs`

```suggestion
```

2024-11-04 10:29 UTC, GSVarsha requested changes
Please add an entry [here](https://github.com/instana/python-sensor/blob/fix_requirements/tests/conftest.py#L33-L39) to prevent running gcs tests on the runtime jobs.

2024-11-05 11:20 UTC, GSVarsha approved these changes
LGTM!

2024-11-11 11:21 UTC, CagriYonca commented
I'm closing this PR. The PR below solves dependency problems with google-cloud package for Python 3.11 and 3.12:
https://github.com/instana/python-sensor/pull/667

2024-11-11 11:22 UTC, CagriYonca commented
I'm closing this PR. The PR below solves dependency problems with google-cloud package for Python 3.11 and 3.12:
https://github.com/instana/python-sensor/pull/667

2024-11-11 11:22 UTC, closed without merging